/*
 * File: app/view/DetailsPanel.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CatHerder.view.itemDetails', {
    extend: 'Ext.Panel',
    alias: 'widget.itemdetails',
    config: {
        ui: '',
        scrollable: true,
        tpl: '<img src="{photoURL}"><br />Catalog#: {itemID}<br />Name: {name}<br />Price: ${price}<br />Description: {description}<br />',
        items: [
            {
                xtype: 'titlebar',
                docked: 'top',
                title: 'Item Name Here',
                items: [
                    {
                        xtype: 'button',
                        ui: 'back',
                        text: 'Back',
                        id: 'BackToItemButton'
                    },
                    {
                        xtype: 'button',
                        text: 'Edit',
                        id: 'editItemButton',
                        align: 'right'
                    }
                ]
            }
        ],
        listeners: [
            {
                fn: 'onEditItemTap',
                event: 'tap',
                delegate: '#editItemButton'
            }, {
                fn: 'onBackItemTap',
                event: 'tap',
                delegate: '#BackToItemButton'
            }
        ]
    },
    onEditItemTap: function(button, e, options) {
        var tabs = button.up('tabpanel');
        var current = tabs.getActiveItem();
        console.log(current);
        var details = current.getActiveItem();
        var rec = details.getRecord();
        console.log(rec);
        current.setActiveItem(1);
        var form = current.getActiveItem();
        form.setRecord(rec);
    },
    onBackItemTap: function(button, e, options) {
        var tabs = button.up('tabpanel');
        var current = tabs.getActiveItem();
        current.setActiveItem(0);
    }

});