/*
 * File: app/view/itemForm.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CatHerder.view.itemForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.itemform',
    config: {
        items: [
            {
                xtype: 'container',
                html: 'Please enter the item information below:',
                id: 'itemText',
                margin: 8,
                style: 'text-align:center;'
            },
            {
                xtype: 'textfield',
                id: 'itemName',
                name: 'name',
                label: 'Name'
            },
            {
                xtype: 'selectfield',
                id: 'categoryID',
                name: 'categoryID',
                margin: '8 0 8 0',
                label: 'Category',
                store: 'categoryStore',
                displayField: 'name',
                valueField: 'categoryID'

            },
            {
                xtype: 'textfield',
                id: 'itemPrice',
                name: 'price',
                margin: '8 0 8 0',
                label: 'Price'
            },
            {
                xtype: 'urlfield',
                id: 'itemPhoto',
                name: 'photoURL',
                margin: '8 0 8 0',
                label: 'Photo',
                placeHolder: 'http://example.com'
            },
            {
                xtype: 'textareafield',
                id: 'itemDescription',
                name: 'description',
                label: 'Description'
            },
            {
                xtype: 'hiddenfield',
                id: 'itemID',
                name: 'itemID',
                value: 0
            },
            {
                xtype: 'button',
                margin: 8,
                ui: 'confirm',
                text: 'Save',
                handler: function() {
                    var form = this.up('formpanel');
                    console.log(form);
                    var store = Ext.getStore('itemStore');
                    var values = form.getValues();
                    console.log(values);
                    if(values.itemID > 0) {
                        console.log('edit');
                        var index = store.find('itemID', values.itemID);
                        var record = store.getAt(index);
                        record.set(values);
                    } else {
                        var record = Ext.ModelMgr.create(form.getValues(), 'CatHerder.model.Item');
                        console.log('add');
                    }
                    record.save();
                    var tabs = this.up('tabpanel');
                    var current = tabs.getActiveItem();
                    console.log(current);
                    current.setActiveItem(0);
                }
            },
            {
                xtype: 'button',
                margin: 8,
                ui: 'decline',
                text: 'Cancel',
                handler: function() {
                    var tabs = this.up('tabpanel');
                    var current = tabs.getActiveItem();
                    console.log(current);
                    current.setActiveItem(0);
                }
            }
        ]
    }

});