/*
 * File: app/view/itemList.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CatHerder.view.itemList', {
    extend: 'Ext.dataview.List',
    alias: 'widget.itemlist',
    config: {
        id: 'itemList',
        itemId: 'mylist',
        store: 'itemStore',
	itemTpl: [
	    '{category.name}: {name}',
	    '<p class="delete" style="position: absolute; right: 5px; top: 20px; display: none;">',
 	    '<img src="resources/images/delete.png" alt="delete" />',
 	    '</p>'
	],
        listeners: [
            {
                fn: 'onMylistItemSwipe',
                event: 'itemswipe'
            },
            {
                fn: 'onMylistItemTaphold',
                event: 'itemtaphold'
            },
            {
                fn: 'onMylistItemSingletap',
                event: 'itemsingletap'
            }
        ],
	isDeleting: false
    },

    onMylistItemSwipe: function(dataview, index, target, record, e, options) {
	var delBtn = target.down('.delete');
	Ext.Anim.run(delBtn, 'fade', {
			out: false,
			duration: 200
	});
	// event
	delBtn.on('tap', function() {
	    console.log('Tapped Delete');
	    console.log(arguments);
//	    this.deleteItem()
	}, dataview, {
	    single: true
	});


	if (this.isDeleting) {
	    //Hide other delete button.
	    this.isDeleting.hide();
	    this.isDeleting = delBtn;
	}
    },

    onMylistItemTaphold: function(dataview, index, target, record, e, options) {
        console.log('Item Tap Hold');
    },

    onMylistItemSingletap: function(dataview, index, target, record, e, options) {
        console.log('Item Single Tap');
    }

});