/*
 * File: app/view/Main.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CatHerder.view.Main', {
    extend: 'Ext.tab.Panel',

    config: {
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                title: 'Cat Herder',
                items: [
                    {
                        xtype: 'spacer'
                    },
                    {
                        xtype: 'button',
                        itemId: 'addButton',
                        ui: 'action',
                        text: 'Add'
                    }
                ]
            },
            {
                xtype: 'container',
                id: 'items',
                layout: {
                    type: 'card'
                },
                title: 'Items',
                iconCls: 'info',
		items: [
		    {xtype: 'itemlist'},
		    {xtype: 'itemform'},
            {xtype: 'itemdetails'}
		]
            },
            {
                xtype: 'container',
                layout: {
                    type: 'card'
                },
                title: 'Categories',
                iconCls: 'info',
                items: [
                    {xtype: 'categorylist'},
                    {xtype: 'categoryform'},
                    {xtype: 'categorydetails'}
                ]
            }
        ],
        tabBar: {
            docked: 'bottom'
        },
        listeners: [
            {
                fn: 'onAddButtonTap',
                event: 'tap',
                delegate: '#addButton'
            }
        ]
    },

    onAddButtonTap: function(button, e, options) {
        var tabs = button.up('tabpanel');
        var current = tabs.getActiveItem();
        console.log(current);
        current.setActiveItem(1);
    }

});