/*
 * File: app/view/Main.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CatHerder.view.Main', {
    extend: 'Ext.tab.Panel',

    config: {
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                title: 'Cat Herder',
                items: [
                    {
                        xtype: 'spacer'
                    },
                    {
                        xtype: 'button',
                        itemId: 'mybutton5',
                        ui: 'action',
                        text: 'Add'
                    }
                ]
            },
            {
                xtype: 'container',
                id: 'items',
                layout: {
                    type: 'card'
                },
                title: 'Items',
                iconCls: 'info',
		items: [
		    {xtype: 'itemlist'},
		    {xtype: 'itemform'}
		]
            },
            {
                xtype: 'container',
                layout: {
                    type: 'card'
                },
                title: 'Categories',
                iconCls: 'info'
            }
        ],
        tabBar: {
            docked: 'bottom'
        },
        listeners: [
            {
                fn: 'onMybutton5Tap',
                event: 'tap',
                delegate: '#mybutton5'
            }
        ]
    },

    onMybutton5Tap: function(button, e, options) {
        var tabs = button.up('tabpanel');
        console.log(tabs);
        console.log(tabs.getActiveItem());
        if(tabs.getActiveItem().id == "itemList") {
            console.log('show item form');
            var panel = Ext.create('CatHerder.view.itemForm');
            tabs.add(panel);
            panel.show();
        } else {
            console.log('show category form');

        }
    }

});