/*
 * File: app/view/Main.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CatHerder.view.Main', {
    extend: 'Ext.tab.Panel',

    config: {
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                title: 'Cat Herder'
            },
            {
                xtype: 'list',
                itemId: 'mylist',
                store: 'itemStore',
                title: 'Items',
                iconCls: 'info'
            },
            {
                xtype: 'list',
                itemTpl: [
                    '<div>List Item {string}</div>'
                ],
                store: 'categoryStore',
                title: 'Categories',
                iconCls: 'info'
            }
        ],
        tabBar: {
            docked: 'bottom'
        },
        listeners: [
            {
                fn: 'onMylistItemSwipe',
                event: 'itemswipe',
                delegate: '#mylist'
            },
            {
                fn: 'onMylistItemTaphold',
                event: 'itemtaphold',
                delegate: '#mylist'
            },
            {
                fn: 'onMylistItemSingletap',
                event: 'itemsingletap',
                delegate: '#mylist'
            }
        ]
    },

    onMylistItemSwipe: function(dataview, index, target, record, e, options) {
        console.log('Item Swiped');
    },

    onMylistItemTaphold: function(dataview, index, target, record, e, options) {
        console.log('Item Tap Hold');
    },

    onMylistItemSingletap: function(dataview, index, target, record, e, options) {
        console.log('Item Single Tap');
    }

});