/*
 * File: app/model/Category.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CatHerder.model.Category', {
    extend: 'Ext.data.Model',
    config: {
        idProperty: 'categoryID',
        fields: [
            {
                name: 'categoryID',
                type: 'int'
            },
            {
                name: 'name'
            }
        ],
        hasMany: {
            model: 'CatHerder.model.Item',
            name: 'items',
	    foreignKey: 'categoryID',
	    autoLoad: true
	},
	proxy: {
	    type: 'rest',
	    url: '/api/category'
	}
    }
});